apiVersion: v1
kind: Service
metadata:
  name: moctail-service
spec:
  type: LoadBalancer
  selector:
    app: mocktail
  ports:
    - protocol: TCP
      port: 7082
      targetPort: 7080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocktail
  labels:
    app: mocktail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocktail
  template:
    metadata:
      labels:
        app: mocktail
    spec:
      containers:
      - name: mocktail
        image: hhaluk/mocktail:v1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7080
    
